version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '27081:80'  # 将本地的 27081 端口映射到容器的 80 端口
    container_name: wxcloud_wxcloudrun-flask
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ADDRESS=${MYSQL_ADDRESS}
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - UPLOAD_FOLDER=/app/uploads/
    networks:
      - wxcb0
networks:
  wxcb0:
    external: true