version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'  # 将本地的27081端口映射到容器的80端口
    container_name: wxcloud_wxcloudrun-flask
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=wxcloudrun-flask
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Moshou99
      - MYSQL_ADDRESS=10.4.102.132:3306
      - SECRET_KEY=your_secret_key
      - OPENAI_API_KEY=your_openai_api_key
      - OPENAI_MODEL=gpt-4
      - UPLOAD_FOLDER=/app/uploads/
    networks:
      - wxcb0
networks:
  wxcb0:
    external:
      name: wxcb0