version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'  # 将本地的 27081 端口映射到容器的 80 端口
    container_name: wxcloud_wxcloudrun-flask
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=wxcloudrun-flask
      - role=container
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ADDRESS=${MYSQL_ADDRESS}
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
    networks:
      - wxcb0
networks:
  wxcb0:
    external:
      name: wxcb0